FROM mcr.microsoft.com/dotnet/runtime:7.0-alpine AS base
WORKDIR /app

# copy csproj and restore as distinct layers
FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build
WORKDIR /src
COPY ["Neal.Twitter.Infrastructure.StreamReader/Neal.Twitter.Infrastructure.StreamReader.csproj", "."]
COPY ["Neal.Twitter.Application/Neal.Twitter.Application.csproj", "."]
COPY ["Neal.Twitter.Core/Neal.Twitter.Core.csproj", "."]
RUN dotnet restore Neal.Twitter.Infrastructure.StreamReader.csproj -r linux-musl-x64 /p:PublishReadyToRun=true
COPY Neal.Twitter.Infrastructure.StreamReader/ .
RUN dotnet publish Neal.Twitter.Infrastructure.StreamReader.csproj -c Release -o /publish -r linux-musl-x64 --self-contained true --no-restore /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:PublishSingleFile=true

# final stage/image
FROM mcr.microsoft.com/dotnet/runtime-deps:7.0-alpine-amd64
WORKDIR /app
COPY --from=build /publish .
ENTRYPOINT ["dotnet", "Neal.Twitter.Infrastructure.StreamReader.dll]
